### ISSUE TITLE
20news task,  跑完main_loop之后，找不到model 

### ISSUE THREAD

**Issue by charles0-0** [Sleepychord/CogLTX#10]
---运行了main_loop 之后没有save_dir，但是log_dir 里面有checkpoints文件夹，里面有.ckpt文件
Traceback (most recent call last):
  File "/Users/liyong/openSource/CogLTX/run_20news.py", line 58, in <module>
    for qbuf, dbuf, buf, relevance_score, ids, output in prediction(config):
  File "/Users/liyong/openSource/CogLTX/main_loop.py", line 74, in prediction
    intro_model = IntrospectorModule.load_from_checkpoint(find_lastest_checkpoint(os.path.join(config.save_dir, 'introspector', f'version_{config.version}', 'checkpoints'))).to(device).eval()
  File "/Users/liyong/opt/anaconda3/envs/cogLTX/lib/python3.6/site-packages/pytorch_lightning/core/lightning.py", line 1501, in load_from_checkpoint
    checkpoint = torch.load(checkpoint_path, map_location=lambda storage, loc: storage)
  File "/Users/liyong/opt/anaconda3/envs/cogLTX/lib/python3.6/site-packages/torch/serialization.py", line 419, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/liyong/openSource/CogLTX/save_dir/introspector/version_0/checkpoints/'

**Comment by charles0-0** [comment]
Trainer里面设置了logger 和 save_dir， 就自动存在了log_dir里面， 然后碰到https://github.com/Sleepychord/CogLTX/issues/4 一样的问题

**Comment by zhci** [comment]
> Trainer里面设置了logger 和 save_dir， 就自动存在了log_dir里面， 然后碰到#4 一样的问题

hi,兄弟你怎么解决这个的，我也遇到这个了

**Comment by GoXian** [comment]
请问 你测试的在 20 news 这个数据集上的表现怎么样，和TextCNN或者是fastText相比较。
