### ISSUE TITLE
pickle error

### ISSUE THREAD

**Issue by nzy1998** [Sleepychord/CogLTX#2]
When I run run_20news.py, here comes the error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'conditional_trans_classification' on <module '__mp_main__' from '/data/CogLTX/run_20news.py'>

I wonder why it happens,please！

**Comment by OPilgrim** [comment]
Me too!!! Have you solved it yet?

**Comment by OPilgrim** [comment]
> When I run run_20news.py, here comes the error:
> 
> Traceback (most recent call last):
> File "", line 1, in
> File "/usr/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
> exitcode = _main(fd)
> File "/usr/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
> self = reduction.pickle.load(from_parent)
> AttributeError: Can't get attribute 'conditional_trans_classification' on <module '**mp_main**' from '/data/CogLTX/run_20news.py'>
> 
> I wonder why it happens,please！

Me too!!! Just move def conditional_trans_classification() out of  if __name__ == "__main__"
