### ISSUE TITLE
Checkpoint contains hyperparameters but IntrospectorModule's __init__ is missing the argument 'hparams'. 

### ISSUE THREAD

**Issue by exol-forlife** [Sleepychord/CogLTX#4]
/home/anaconda3/envs/cogltx/lib/python3.7/site-packages/pytorch_lightning/utilities/warnings.py:18: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` in the `DataLoader` init to improve performance.
  warnings.warn(*args, **kwargs)
Traceback (most recent call last):
  File "run_20news.py", line 45, in <module>
    main_loop(config)
  File "/data/CogLTX-main/main_loop.py", line 57, in main_loop
    trainer.fit(introspector)
  File "/home/anaconda3/envs/cogltx/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 695, in fit
    self.load_spawn_weights(model)
  File "/home/anaconda3/envs/cogltx/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_data_parallel.py", line 373, in load_spawn_weights
    loaded_model = original_model.__class__.load_from_checkpoint(path)
  File "/home/anaconda3/envs/cogltx/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1509, in load_from_checkpoint
    model = cls._load_model_state(checkpoint, *args, **kwargs)
  File "/home/anaconda3/envs/cogltx/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1533, in _load_model_state
    f"Checkpoint contains hyperparameters but {cls.__name__}'s __init__ "
pytorch_lightning.utilities.exceptions.MisconfigurationException: Checkpoint contains hyperparameters but IntrospectorModule's __init__ is missing the argument 'hparams'. Are you loading the correct checkpoint?

**Comment by exol-forlife** [comment]
请问你有遇到这个问题吗

/home/anaconda3/envs/cogltx/lib/python3.7/site-packages/pytorch_lightning/utilities/warnings.py:18: UserWarning: The dataloader, train dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the num_workers argumentin theDataLoader` init to improve performance.
warnings.warn(*args, **kwargs)
Traceback (most recent call last):
File "run_20news.py", line 45, in
main_loop(config)
File "/data/CogLTX-main/main_loop.py", line 57, in main_loop
trainer.fit(introspector)
File "/home/anaconda3/envs/cogltx/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 695, in fit
self.load_spawn_weights(model)
File "/home/anaconda3/envs/cogltx/lib/python3.7/site-packages/pytorch_lightning/trainer/distrib_data_parallel.py", line 373, in load_spawn_weights
loaded_model = original_model.class.load_from_checkpoint(path)
File "/home/anaconda3/envs/cogltx/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1509, in load_from_checkpoint
model = cls._load_model_state(checkpoint, *args, **kwargs)
File "/home/anaconda3/envs/cogltx/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py", line 1533, in _load_model_state
f"Checkpoint contains hyperparameters but {cls.name}'s init "
pytorch_lightning.utilities.exceptions.MisconfigurationException: Checkpoint contains hyperparameters but IntrospectorModule's init is missing the argument 'hparams'. Are you loading the correct checkpoint?

**Comment by miaomi1994** [comment]
@exol-forlife hi~,did you solve the problem?

**Comment by exol-forlife** [comment]
I couldn't find a solution to it, so I rewrote the code using pytorch rather than pytorch-lightning, but the result was not satisfying :(

**Comment by exol-forlife** [comment]
> @exol-forlife hi~,did you solve the problem?

I couldn't find a solution to it, so I rewrote the code using pytorch rather than pytorch-lightning, but the result was not satisfying :(

**Comment by miaomi1994** [comment]
> > @exol-forlife hi~,did you solve the problem?
> 
> I couldn't find a solution to it, so I rewrote the code using pytorch rather than pytorch-lightning, but the result was not satisfying :(

Do you mean that the result is not as stated in the paper?

**Comment by Sleepychord** [comment]
hi, sorry for ignoring the problem before. I think this is because this repo depends on a old version of pytorch-lightning. 
@exol-forlife could you describe more about your re-implementation problem?

**Comment by miaomi1994** [comment]
I update the pytorch-lightning to 0.7.3 and still have this problem @Sleepychord

**Comment by ParanoidW** [comment]
> I update the pytorch-lightning to 0.7.3 and still have this problem @Sleepychord

Hi, I have the same question. Did you solve this? @miaomi1994

**Comment by ParanoidW** [comment]
Same question in pytorch-lightning 0.6.0 or 0.7.3, looks like the version provided in README is wrong. @Sleepychord @dm-thu Please give some help.

**Comment by yudong27** [comment]
modify paramters in class IntrospectorModule(pl.LightningModule) __init__ function and code in below
change: def __init__(self, config): ==> def __init__(self, hparams)
add config = hparams

so do class ReasonerModule
